### ISSUE TITLE
转换xmind格式化以后用Xmind无法打开

### ISSUE THREAD

**Issue by java666888** [jan-bar/mindmap_to_xmind#1]
用项目中的input.mindmap的文件来转换,然后使用Xmind也无法打开 提示错误
![image](https://user-images.githubusercontent.com/51404448/201514110-cf0d3d4b-4e9e-4577-a2cf-5fa47471ae7d.png)

**Comment by jan-bar** [comment]
这个项目的Python库是xmind官方的额，不过我记得xmind8和之前的版本格式不兼容。我这个项目都是在我电脑上用xmind8试过可以打开额。

**Comment by java666888** [comment]
好的,那我去下载个旧版本先,感谢
