### ISSUE TITLE
希望作者能将mindmap_new.py代码打包成可执行文件

### ISSUE THREAD

**Issue by Narut0123** [jan-bar/mindmap_to_xmind#2]
希望作者能将mindmap_new.py代码打包成可执行文件mindmap_new.exe
方便通过cmd命令转换文件
谢谢！

**Comment by jan-bar** [comment]
@Narut0123 
之前因为没找到go的xmind库只能用Python搞，但是Python编译可执行程序比较蛋疼。所以我自己搞了个go语言的xmind库。看到你有这个需求我就为这个项目添加一个go语言的实现吧，可执行程序 [下载](https://github.com/jan-bar/mindmap_to_xmind/blob/master/mindmap_to_xmind/mindmap.exe)

可以参考: [源码](https://github.com/jan-bar/mindmap_to_xmind/blob/master/mindmap_to_xmind/main.go)

执行命令: `.\mindmap.exe -db "C:\Users\xxx\AppData\Roaming\ynote-desktop\your_name@163.com\ynote-data\your_name@163.com.db" -title "%.mindmap" -dst "save.xmind"`

**Comment by Narut0123** [comment]
万分感谢大佬

**Comment by Narut0123** [comment]
> @Narut0123 之前因为没找到go的xmind库只能用Python搞，但是Python编译可执行程序比较蛋疼。所以我自己搞了个go语言的xmind库。看到你有这个需求我就为这个项目添加一个go语言的实现吧，可执行程序 [下载](https://github.com/jan-bar/mindmap_to_xmind/blob/master/mindmap_to_xmind/mindmap.exe)
> 
> 可以参考: [源码](https://github.com/jan-bar/mindmap_to_xmind/blob/master/mindmap_to_xmind/main.go)
> 
> 执行命令: `.\mindmap.exe -db "C:\Users\xxx\AppData\Roaming\ynote-desktop\your_name@163.com\ynote-data\your_name@163.com.db" -title "%.mindmap" -dst "save.xmind"`

请问大佬，如果是直接转换某路径下的".mindmap"文件，该执行什么命令呢？

**Comment by jan-bar** [comment]
@Narut0123 
加了个参数，你重新下载试试吧

转换单个文件: `.\mindmap.exe -file "C:\Users\xxx\AppData\Roaming\ynote-desktop\your_name@163.com\ynote-data\file\C\xxx" -dst "save.xmind"`

**Comment by Narut0123** [comment]
> mindmap.exe -file "C

试了一下，转换成功！但是线条没有色彩了，变成黑色线条了。之前用py代码打包的exe可执行文件转换的结果线条是有颜色的

**Comment by jan-bar** [comment]
> > mindmap.exe -file "C
> 
> 试了一下，转换成功！但是线条没有色彩了，变成黑色线条了。之前用py代码打包的exe可执行文件转换的结果线条是有颜色的

这个你去研究吧，我那个xmind库也说了，只管内容不管样式。Python那个毕竟是xmind官方库。你可以用zip软件打开xmind文件研究里面的格式吧。。那太复杂了，我没有深入的想法。 你可以继续用Python的库吧

**Comment by Narut0123** [comment]
> 

thanks anyway
